name: Local Pipeline Test

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: 

jobs:
  test-connection:
    name: Control My Laptop
    runs-on: self-hosted

    steps:
      - name: Create a Text File
        run: echo "SUCCESS! GitHub Actions is talking to my laptop!" > Pipeline_Proof.txt

      - name: Open Notepad
        run: start notepad.exe
